development: &development
  protocol: 'http'
  host: localhost
  port: 5984
  prefix: issue_tracker
  suffix: development
  username:
  password:

test:
  <<: *development
  suffix: test

production:
  protocol: 'https'
  host: localhost
  port: 5984
  prefix: issue_tracker
  suffix: production
  username: root
  password: 123